#!/usr/bin/env bash

#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local url_consul_Darwin='https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_darwin_amd64.zip'
  local url_consul_Linux='https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_amd64.zip'

  local tmp_consul="$(mktemp -t XXXXXX)"
  trap "$(printf "rm -f '%q'" "$tmp_consul")" EXIT
  local url_consul="url_consul_$(uname -s)"
  curl -sS -L -o "$tmp_consul" "${!url_consul}"
  cd bin
  unzip -o "$tmp_consul"
  chmod 755 consul
}

bootstrap
