#!/usr/bin/env bash

function profile {
  local shome="${_consul_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  export CONSUL_VERSION="0.6.4"
}

profile
