#!/usr/bin/env bash

function consul_server {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    bootstrap|server)
      exec consul agent -config-dir="${shome}/etc" -advertise "${CACHE_VIP}" -server -bootstrap ${CONSUL_NODE:+-node "$CONSUL_NODE"}
      ;;
    default|agent)
      exec consul agent -config-dir="${shome}/etc" -advertise "$(facts '[.fan_250,.eth1,.br0] | map(select(length > 0))[-1].ipv4.address' | head -1)" -join "${CACHE_VIP}" ${CONSUL_NODE:+-node "$CONSUL_NODE"}
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

consul_server "$@"
