#!/usr/bin/env bash

function consul_server {
  local shome="${_consul_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"
  source "$HOME/.bashrc"

  cd "$shome"
  case "${1:-}" in
    join)
      exec consul agent -config-dir="${shome}/etc" -advertise "$(facts -r '.eth1.ipv4.address')" -join "${CACHE_VIP}"
      ;;
    *)
      exec consul agent -config-dir="${shome}/etc" -advertise "${CACHE_VIP}" -server -bootstrap
      ;;
  esac
}

consul_server "$@"
