#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_consul="$(consul --version 2>/dev/null | awk 'NR == 1 {print $2}' | perl -pe 's{^v}{}' || true)"
  jq -n --arg consul "$ver_consul" '{consul: $consul}'
}

version "$@"
